Application/asignacion/__init__.py
from flask import Blueprint
asignacion = Blueprint('asignacion_general', __name__, template_folder='templates', static_folder='static')
from . import routes
from . import Actualizar_pedidos

Application/asignacion/routes.py
from flask import Flask, render_template, request, redirect, url_for, flash, jsonify
from flask.json import load
import pandas as pd
from pandas.core.frame import DataFrame
import datetime
import os.path, sys
import json
sys.path.append(os.path.join(os.path.dirname(os.path.realpath(__file__)), os.pardir))
from PostgreeConnDB import PostgreeConnDB
from config.loadData import readJson
from . import asignacion
from . import Actualizar_pedidos



#settings
asignacion.secret_key = "770071010"

#Creamos la variable global last_ofs para agilizar las querys individuales   
datosIni = readJson()
sql = PostgreeConnDB("BonnysaDB")
last_ofs = sql.select_ofs_by_date(14)


 

@asignacion.route("/asignaciones")
def Index():

    return render_template("asignaciones.html")

@asignacion.route("/getAsignacionesData")
def getAsignacionesData():
    #Querys en la base de datos
    pedidos = sql.select_orders(7) # El número define los días por dentrale y por detras del actual, del que se quieren registros
    ofs = sql.select_ofs_by_date(14)
    global last_ofs 
    last_ofs = ofs

    #Campos adicionales a la base de datos para cuadrar con el front
    pedidos['check'] = ""
    pedidos['desplegable'] = ""
    pedidos['palets_sin_asignar'] = pedidos['num_palets'] - pedidos['palets_asig']

    #Cambiar formatos de fecha datetime a string
    pedidos['fecha_carga'] = pedidos['fecha_carga'].map(lambda ts: ts.strftime("%Y-%m-%d"))
    pedidos['fecha_entrega'] = pedidos['fecha_entrega'].map(lambda ts: ts.strftime("%Y-%m-%d"))
    pedidos['fecha_produccion'] = pedidos['fecha_produccion'].map(lambda ts: ts.strftime("%Y-%m-%d"))
    pedidos['producto'] = pedidos['codigo_producto']+'-'+pedidos['producto']
    pedidos['cliente'] =  pedidos['codigo_cliente']+'-'+pedidos['cliente']
    #dataframe ordenado para formatear a array de arrays
    etl_pedidos = pedidos[['check','desplegable','id','fecha_carga', 'fecha_entrega', 'fecha_produccion', 'num_pedido',  'producto', 'articulo',\
        'lote_cliente', 'cliente', 'num_palets', 'cajas', 'linea', 'palets_asig', 'palets_completos', 'palets_sin_asignar', 'nombre_estado']]

    #Crear un array de arrays de pedidos
    array_of_arrays = etl_pedidos.to_dict('split')

    return  array_of_arrays

@asignacion.route("/getOfAsignacion", methods = ["POST","GET"])
def getOfAsignacion():
    # Transformar el valor de petición a un int
    idpedido = request.args['data']
    ofs = last_ofs.loc[last_ofs['id_pedido'] == int(idpedido)]
    ofs = ofs.set_index('id')
    #dataframe ordenado para formatear a array de arrays
    etl_ofs = ofs[['status', 'originalquantity', 'destrio', 'description', 'linea_id', 'quantity']]
    #Crear un array de arrays de pedidos
    array_of_arrays = etl_ofs.to_dict('split')

    return  array_of_arrays

@asignacion.route("/asignaciondirecta", methods = ["POST","GET"])
def asignaciondirecta():
    column_names = ['error', 'id_pedido', 'id', 'status', 'originalquantity', 'destrio', 'description', 'linea_id', 'quantity']
    res = pd.DataFrame(columns = column_names)
    response = request.get_json()
    for i in response['obj']['pedidos']:
        try:
            #Comparamos los pallets antiguos con los nuevos y modificamos el pedido
            pedido = sql.select_pedido_by_id(i)

            date = datetime.datetime.today()
            pallets = pedido["palets_asig"][0]
            line = response['obj']['linea']
            
            #Buscamos el id de la línea asignada
            devices = sql.select_devices()
            idline = int(devices.loc[devices['linea'] == int(line), 'id'])
            incidencias = sql.select_linea_incidencia_by_id(idline)
            events = sql.select_standar_events()

            incidencia_1 = events.loc[(events.id == int(incidencias.iloc[0]['id_event_1']), ['description'])].values[0][0]
            incidencia_2 = events.loc[(events.id == int(incidencias.iloc[0]['id_event_2']), ['description'])].values[0][0]
            incidencia_3 = events.loc[(events.id == int(incidencias.iloc[0]['id_event_3']), ['description'])].values[0][0]
            incidencia_4 = events.loc[(events.id == int(incidencias.iloc[0]['id_event_4']), ['description'])].values[0][0]
            incidencia_5 = events.loc[(events.id == int(incidencias.iloc[0]['id_event_5']), ['description'])].values[0][0]
            incidencia_6 = events.loc[(events.id == int(incidencias.iloc[0]['id_event_6']), ['description'])].values[0][0]
            incidencia_7 = events.loc[(events.id == int(incidencias.iloc[0]['id_event_7']), ['description'])].values[0][0]
            incidencia_8 = events.loc[(events.id == int(incidencias.iloc[0]['id_event_8']), ['description'])].values[0][0]
            incidencia_9 = events.loc[(events.id == int(incidencias.iloc[0]['id_event_9']), ['description'])].values[0][0]          
            
            """ que asigne un orden a las lineas nuevas """
            orden = sql.select_max_orden()
            if orden["orden"][0] is None:
                max_orden = 1
            else: 
                max_orden =int(orden["orden"][0]) + 1
            
            #ver que los campos encajen
            ofid = sql.insert_r('ofs','(of,description,quantity,model,status,originalquantity,okquantity,incidenciatop1,incidenciatop2,incidenciatop3,incidenciatop4,incidenciatop5,incidenciatop6,incidenciatop7,incidenciatop8,incidenciatop9,cicletime,cajas,destrio,linea,creation,id_pedido,linea_id,ruta,cliente,fecha_carga,fecha_produccion,lote_cliente, orden)',\
                (pedido["num_pedido"][0],pedido["descripcion"][0],pallets,pedido["articulo"][0],'new',pallets,"1",incidencia_1,incidencia_2,incidencia_3,incidencia_4,incidencia_5,incidencia_6,incidencia_7,incidencia_8,incidencia_9,"1",pedido["cajas"][0],"0",str(idline),str(date),pedido["id"][0],str(response['obj']['linea']),pedido["ruta"][0],pedido["cliente"][0],str(pedido["fecha_carga"][0]),str(pedido["fecha_produccion"][0]),pedido["lote_cliente"][0], max_orden))
            
            sql.modify('pedidosllanos',"palets_asig",0,str(pedido['id'][0]))

            row = sql.select_of_by_id(ofid[0][0])
            
            #dataframe ordenado para formatear a array de arrays
            res_row = row[['id_pedido', 'id', 'status', 'originalquantity', 'destrio', 'description', 'linea_id', 'quantity']]
            res_row.loc[:, "error"] = 'False'

            res = res.append(res_row)

        except Exception as e:
            print(e)
            res_row = pd.DataFrame(data = ['True',0,0,0,0,0,0,0,0] ,columns = column_names)
            res = res.append(res_row)

    
    res = res.set_index('id')
    #Crear un array de arrays de pedidos
    array_of_arrays = res.to_dict('split')
    
    pedidos = []
    for i in response['obj']['pedidos']:
        pedido = sql.select_pedido_by_id(i).to_dict('split')
        pedidos.append(pedido['data'][0])

    array_of_arrays['pedidos'] = pedidos
    return array_of_arrays

@asignacion.route("/asignacionparcial", methods = ["POST","GET"])
def asignacionparcial():
    column_names = ['error', 'id_pedido', 'id', 'status', 'originalquantity', 'destrio', 'description', 'linea_id', 'quantity']
    res = pd.DataFrame(columns = column_names)
    
    response = request.get_json()
    
    for i in range(len(response['partialAsign'])): #me falta el id de pedido en cada objeto
        try:
            #Comparamos los pallets antiguos con los nuevos y modificamos el pedido
            pedido = sql.select_pedido_by_id(response['partialAsign'][i]['idpedido'])

            date = datetime.datetime.today()
            pallets = response['partialAsign'][i]['cant']
            line = response['partialAsign'][i]['lane']
            
            #Buscamos el id de la línea asignada
            devices = sql.select_devices()
            idline = int(devices.loc[devices['linea'] == int
            (line), 'id'])
            incidencias = sql.select_linea_incidencia_by_id(idline)
            events = sql.select_standar_events()

            incidencia_1 = events.loc[(events.id == int(incidencias.iloc[0]['id_event_1']), ['description'])].values[0][0]
            incidencia_2 = events.loc[(events.id == int(incidencias.iloc[0]['id_event_2']), ['description'])].values[0][0]
            incidencia_3 = events.loc[(events.id == int(incidencias.iloc[0]['id_event_3']), ['description'])].values[0][0]
            incidencia_4 = events.loc[(events.id == int(incidencias.iloc[0]['id_event_4']), ['description'])].values[0][0]
            incidencia_5 = events.loc[(events.id == int(incidencias.iloc[0]['id_event_5']), ['description'])].values[0][0]
            incidencia_6 = events.loc[(events.id == int(incidencias.iloc[0]['id_event_6']), ['description'])].values[0][0]
            incidencia_7 = events.loc[(events.id == int(incidencias.iloc[0]['id_event_7']), ['description'])].values[0][0]
            incidencia_8 = events.loc[(events.id == int(incidencias.iloc[0]['id_event_8']), ['description'])].values[0][0]
            incidencia_9 = events.loc[(events.id == int(incidencias.iloc[0]['id_event_9']), ['description'])].values[0][0]          

            #ver que los campos encajen
            """ que asigne un orden a las lineas nuevas """
            orden = sql.select_max_orden()
            max_orden =int(orden["orden"][0]) + 1
            ofid = sql.insert_r('ofs','(of,description,quantity,model,status,originalquantity,okquantity,incidenciatop1,incidenciatop2,incidenciatop3,incidenciatop4,incidenciatop5,incidenciatop6,incidenciatop7,incidenciatop8,incidenciatop9,cicletime,cajas,destrio,linea,creation,id_pedido,linea_id,ruta,cliente,fecha_carga,fecha_produccion,lote_cliente, orden)',\

Application/templates/asignacion.html
{% extends "layout.html" %}
{% block body %}

{% with messages = get_flashed_messages()%}
  {%if messages %}

    {%for message in messages%}
      <div class="alert alert-dismissible alert-info">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
          <strong>Mensaje del Servidor: </strong> <a href="#" class="alert-link">{{message}}</a>, revise que la información esté correcta en la tabla inferior.
      </div>
    {% endfor %}

  {% endif %}
{% endwith %}
  
<h1 align="center" class="col-md-12">Asignación de pedido a Líneas</h1>
  <div class="jumbotron">
    <h3>Pedido Seleccionado</h3>
    <table class="table table-hover">
      <thead>
        <tr class="table-primary">
          <th scope="col">Código Pedido</th>
          <th scope="col">Nº de Palets original</th>
          <th scope="col">Cliente</th>
          <th scope="col">COM</th>
          <th scope="col">Palets Restantes por asignar</th>
          <th scope="col">Crear</th>
        </tr>
      </thead>
      <tr>
      {% for selec in selection %}
          <td>{{ selec.1 }}</td>
          <td>{{ selec.4 }}</td>
          <td>{{ selec.7 }}</td>
          <td>{{ selec.3 }}</td>
          <td>{{ selec.5 }}</td>
      {% endfor %}
          <td><button type="number" name="pedido" data-toggle="modal" data-target="#Editmodal" class="btn btn-primary">Crear</button></td>
      </tr>
    </table>
  </div>

  <div class="jumbotron">
    <h3>OFs Asociadas</h3>
    <table class="table table-hover">
	
      <thead>
        <tr class="table-primary">
	      <th scope="col"></th>
        <th scope="col">Código Pedido</th>
        <th scope="col">Estado</th>
        <th scope="col">Palets asignados</th> 
        <th scope="col">Cajas</th>
        <th scope="col">Cliente</th>
        <th scope="col">COM</th>
        <th scope="col">Descripción</th>
        <th scope="col">Línea</th>
        <th scope="col">Pend. Fabricar</th>
        <th scope="col">Editar</th>
        <th scope="col"></th>
        <th scope="col">Borrar</th>
        <th scope="col"></th>
        </tr>
      </thead>
      {% for pedido in pedidos %}
      <form action="/select_line" method="POST" >
      <tr>
	  <td><input type="hidden" name="id"  value="{{ pedido.0}}" readonly><br></td>
          <td>{{ pedido.1 }}</td>
          <td>{{ pedido.5 }}</td>
          <td><input type="number" class="form-control" value="{{ pedido.6 }}" name="palets">
          <td>{{ pedido.18 }}</td>
          <td>{{ pedido.25 }}</td>
          <td>{{ pedido.4 }}</td>
          <td>{{ pedido.2 }}</td>
          <td><select class="form-control col-md-12" name ="linea" placeholder="Selección de Línea">
              <option value="{{ pedido.23 }}">{{ pedido.23}}</option>
              <option value="997">997</option>
	            <option value="999">999</option>
              <option value="15">15</option>
              <option value="16">16</option>
              <option value="17">17</option>
              <option value="36">36</option>
              <option value="38">38</option>
              <option value="39">39</option>
            </select></td>
          <td>{{ pedido.3 }}</td>
          <td><button type="number" name="action" value="edit" class="btn btn-warning">Aplicar</button></td>
          {% for selec in selection %}
            <td><input type="hidden" name="idpedido"  value="{{ selec.0}}" readonly><br></td>
          {% endfor %}
          <td><button type="number" name="action" value="erase" class="btn btn-danger">Borrar</button></td>
      </tr>
      
      </form>
{% endfor %}
    </table>
  </div>

<!-- Modal Crear -->
<div class="modal fade" id="Editmodal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="EditmodallLabel">Creación de OFs</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form action="/select_line" method="POST" >
          <h3>Pedido Seleccionado</h3>
          {% for selec in selection %}
            <input type="hidden" name="id"  value="{{ selec.0 }}" readonly><br><br>
            <h5>Código Pedido: {{ selec.1 }}</h5>
            <input type="hidden" name="pedido"  value="{{ selec.1 }}" readonly><br><br>
            <h5>COM: {{ selec.3 }}</h5>
            <h5>Palets Restantes: {{ selec.5 }}</h5>
            <h5>Cliente: {{ selec.7 }}</h5>
            <h5>Fecha de Carga: {{ selec.11 }}</h5>
            <h5>Fecha de producción: {{ selec.13 }}</h5>
            <input type="hidden" name="fecha_carga"  value="{{ selec.11 }}" readonly>
            <input type="hidden" name="fecha_produccion"  value="{{ selec.13 }}" readonly>
            <input type="hidden" name="lote_cliente"  value="{{ selec.18 }}" readonly>
            <input type="hidden" name="cliente"  value="{{ selec.7 }}" readonly><br><br>
            <input type="hidden" name="com"  value="{{ selec.3 }}" readonly><br><br>
            <h5>Descripción: {{ selec.14 }}</h5>
            <input type="hidden" name="desc"  value="{{ selec.14 }}" readonly><br><br>
            <input type="hidden" name="cajas"  value="{{ selec.16 }}" readonly><br><br>
            <select class="form-control col-md-12" name ="linea" placeholder="Selección de Línea">
              <option value="15">Línea 15</option>
              <option value="16">Línea 16</option>
              <option value="17">Línea 17</option>
              <option value="36">Línea 36</option>
              <option value="38">Línea 38</option>
              <option value="39">Línea 39</option>
              <option value="997">997</option>
	            <option value="999">Servidor</option>
            </select>
            <input type="number" class="form-control" value="{{ selec.5 }}" name="palets"> 
            <input type="hidden" name="action"  value="create" readonly><br><br>
            <input type="hidden" name="ruta"  value="{{ selec.17 }}" readonly><br><br> 
          {% endfor %}
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <button type="submit"  class="btn btn-primary">Crear</button>
            </div>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}


 

Application/templates/checklist.html
{% extends "layout.html" %}
{% block body %}

<div class = "jumbotron">
    <table class="table table-hover" >
      <thead>
        <tr class="table-primary">
          <td scope="col">Articulo</td>
          <td scope="col">Nombre</td>
          <td scope="col">Cantidad</td>
          <td scope="col">Unidades</td>
          <td scope="col">Checkbox</td>
        </tr>
      </thead>
      {% for part in parts %}
          <tr>
            <td>{{ part.2 }}</td>
            <td>{{ part.7 }}</td>
            <td>{{ part.3 }}</td>
            <td>{{ part.4 }}</td>
            <td> 
              <!--div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input"  id="{{ part.2 }}" >
                <label class="custom-control-label" for="{{ part.2 }}">Marcar que se dispone de material</label>
              </div-->
              <div class="btn-group btn-group-toggle" data-toggle="buttons">
               
                <label class="btn btn-primary active">
                  <input type="checkbox" autocomplete="off"> Marcar que se dispone de material
                </label>
              </div>
            </td>

          </tr>
      {% endfor %}
    </table>
        
    <div class="container">

    <div class="row">
      <form action="/of" method="POST" class = "col">
        <button name="ofcode" value="{{ idof }}" class="btn btn-success col-lg-5">Iniciar</button>
      </form>
      
      <form class = "col">
          <!--button onclick="goBack()" class="btn btn-warning col-lg-5">Retroceder</button-->
          <button onclick="goBack()" class="btn btn-warning col-lg-5">Retroceder</button>
          <!--input type="hidden" name="ofcode"  value="0" readonly><br><br-->
      </form>
    </div>
  </div>
</div>

<script>
  function goBack() {
    window.history.back();
  }
  </script>
		
{% endblock %}

Application/templates/layout.html
<!DOCTYPE html>
<html lang="es">
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<title>Digitalizacion Lineas Envasado</title>
<!--
<meta http-equiv="refresh" content="10">
-->
<head>
<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/bootstrap.css')}}" media="screen" >
<!--script type="text/javascript" src="static/js/jquery-3.3.1.min.js"></script-->
<!--script  src="static/js/jquery-3.3.1.min.js"  crossorigin="anonymous"></script-->
<script src="{{url_for('static', filename='js/jquery-3.3.1.min.js')}}" ></script>
<!--<script type="text/javascript" src="../static/js/jquery-ui-1.12.1/jquery-ui-1.12.1/jquery-ui.min.js"></script>-->

<style>
	body {
		margin-top: -20px;		
	}
.mettler__response {
    display: flex;
    height: 20px;
}
.ligth__container {
    display:flex;
    flex-direction: column;
    padding: 20px;
}
.ligth__onoff {
    display:flex;
    justify-content:center;
}
.ligth_on {
    background-color: green;
    width: 20px;
    height: 20px;
    border-radius: 50%;
}
.ligth_off {
    background-color: red;
    width: 20px;
    height: 20px;
    border-radius: 50%;
}
.ligth_load {
    background-color: orange;
    width: 20px;
    height: 20px;
    border-radius: 50%;
}

.ui-sortable-handle {
	cursor: move;
}
.alert.alert-dismissible.alert-info {	
  	font-size: 1.4em;
	padding-top: 25px;
	height: 80px;
}
IMG.displayed {
    display: block;
	margin-top: 10px;
	width: 100px;
    margin-left: auto;
    margin-right: auto 
}
</style>
	{% block head %}
	{% endblock %}
</head>
<body>   

	
	
	
	<div class="navbar navbar-expand-lg navbar-dark bg-primary">
		{% if ofs %}
			{% for of in ofs %}		    
				<div class="col-md-2" style="padding-top: 0px; padding-bottom: 0%;">
					<h5 style = "color:White;">Código de Pedido</h5>				
					<h5 id="pedido_id" style = "color:White;"><strong>{{of.4}}</strong></h5>	´
				
				</div>
				<div class="col-md-1" style="padding-top: 0px; padding-bottom: 0%;">
					<h5 style = "color:White;">Modelo</h5>				
					<h5 style = "color:White;"><strong>{{of.6}}</strong></h5>				
				</div>
				<div class="col-md-1" style="padding-top: 0px; padding-bottom: 0%;">
					<h5 style = "color:White;">Producto</h5>				
					<h5 style = "color:White;"><strong>{{of.17}}</strong></h5>				
				</div>			
				<div class="col-md-1" style="padding-top: 0px; padding-bottom: 0%;">
					<h5 style = "color:White;">Pallets Iniciales</h5>				
					<h5 style = "color:White;"><strong>{{of.9}}</strong></h5>				
				</div>
				<div class="col-md-2" style="padding-top: 0px; padding-bottom: 0%;">
					<h5 style = "color:White;">Pallets Pendientes</h5>				
					<h5 style = "color:White;"><strong>{{of.3}}</strong></h5>				
				</div>
				<div class="col-md-1" style="padding-top: 0px; padding-bottom: 0%;">
					<h5 style = "color:White;">Lote</h5>				
					<h5 style = "color:White;"><strong>{{of.15}}</strong></h5>				
				</div>
				<div class="col-md-1" style="padding-top: 0px; padding-bottom: 0%;">
					<h5 style = "color:White;">Cajas</h5>				
					<h5 style = "color:White;"><strong>{{of.7}}</strong></h5>				
				</div>	
				<div class="col-md-1" style="padding-top: 0px; padding-bottom: 0%;">
					<h5 style = "color:White;"> <a href="{{ url_for('configuracion_linea') }}" style="color: white;">  Línea  <br> <span id="lineaActual"> </span> </a></h5>
				</div>
			   	
			   <div class="col-md-1" style="padding-top: 0px; padding-bottom: 0%;">
				   <h5 style = "color:White;">Operarios</h5>										
				   <h5 style = "color:White;"><strong>{{operario}}</strong></h5>				
			   </div>
			   		  
			{% endfor %} 
		{% else %}
			<div class="col-md-2 alig-self-center" style="padding-top: 0px; padding-bottom: 0%;">
				<h5 style = "color:White;">Código de Pedido</h5>								
			</div>
			<div class="col-md-1" style="padding-top: 0px; padding-bottom: 0%;">
				<h5 style = "color:White;">Modelo</h5>				
							
			</div>
			<div class="col-md-2" style="padding-top: 0px; padding-bottom: 0%;">
				<h5 style = "color:White;">Producto</h5>				
							
			</div>			
			<div class="col-md-1" style="padding-top: 0px; padding-bottom: 0%;">
				<h5 style = "color:White;">Pallets Iniciales</h5>				
								
			</div>
			<div class="col-md-1" style="padding-top: 0px; padding-bottom: 0%;">
				<h5 style = "color:White;">Pallets Pendientes</h5>				
								
			</div>
			<div class="col-md-1" style="padding-top: 0px; padding-bottom: 0%;">
				<h5 style = "color:White;">Lote</h5>		
							
			</div>
			
			<div class="col-md-1" style="padding-top: 0px; padding-bottom: 0%;">
				<h5 style = "color:White;">Cajas</h5>				
							
			</div>
		<div class="col-md-1" style="padding-top: 0px; padding-bottom: 0%;">
			<h5 style = "color:White;"> <a href="{{ url_for('configuracion_linea') }}" style="color: white;">  Línea  <br> <span id="lineaActual"> </span> </a></h5>
		</div>
		<div class="col-md-1" style="padding-top: 0px; padding-bottom: 0%;">
			<h5 style = "color:White;">Operarios</h5>										
			<h5 style = "color:White;"><strong>{{operario}}</strong></h5>				
		</div>
		{% endif %}
		
    	
    	<div class="col-md-1" style="padding-top: 0px; padding-bottom: 0%;">
    		<img class="btn-group" role="group" id="btnGroupDrop1"  data-toggle="dropdown" src="{{url_for('static', filename='img/LogoMenu.png')}}" alt="Logo Menu"  width="40%"></img>
			   	<div class="dropdown-menu" aria-labelledby="btnGroupDrop1" >
			   		<a href="{{ url_for('Index') }}" style ="text-align: center;" class="list-group-item list-group-item-action" >Inicio</a>
			   		<a href="{{ url_for('login') }}" style ="text-align: center;" class="list-group-item list-group-item-action">Fichajes</a>
			   		<a href="{{ url_for('of') }}" style ="text-align: center;" class="list-group-item list-group-item-action">Orden Fabricación</a>
			   		<a href="{{ url_for('destrio') }}" style ="text-align: center;" class="list-group-item list-group-item-action">Destrío</a>
			   		<a href="{{ url_for('asignacion_general.Index') }}" style ="text-align: center;" class="list-group-item list-group-item-action">Asignación</a>
					   <!-- <a href="{{ url_for('configuracion_linea') }}" style ="text-align: center;" class="list-group-item list-group-item-action">Configuración</a> -->
					<a href="{{ url_for('fichajes_page.operarios') }}" style ="text-align: center;" class="list-group-item list-group-item-action">Fichado Aútomatico</a>
					<a href="{{ url_for('kpi') }}" style ="text-align: center;" class="list-group-item list-group-item-action">KPI AOFS</a>
					<a href="{{ url_for('kpiOfs') }}" style ="text-align: center;" class="list-group-item list-group-item-action">KPI POR OF</a>
			   	</div>
			
    	</div>
	    
	   	
	</div>
	<div id="alert_estado" class="alert alert-danger" role="alert" style="display: none;">
		Este pedido activo ha sido cancelado
	</div>

	
	<!--señales-->
	{% block body %}
	{% endblock %}
	
<!--scripts-->

<!--script  src="static/js/popper.min.js" crossorigin="anonymous"></script-->
<script src="{{url_for('static', filename='js/popper.min.js')}}" crossorigin="anonymous"></script>
<!--script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script-->
<!--script type="text/javascript" href="{{url_for('static', filename='js/bootstrap.min.js')}}" media="screen"></script-->
<!--script type="text/javascript" src="static/js/bootstrap.min.js"></script-->
<!--script src="static/js/bootstrap.min.js" crossorigin="anonymous"></script-->
<script src="{{url_for('static', filename='js/bootstrap.min.js')}}" crossorigin="anonymous"></script>
<!--script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script-->
<footer>
	
</footer>
</body>
</html>
<script>
 $(document).ready(function(e) {	
	getEstado()
    setInterval(() => getEstado(), 10000);
 });

 function getEstado() {
	let valor = $( "#pedido_id" ).text();		
	if (valor !== undefined && valor != "")
	{
		console.log(valor);	
		let json = {"id": valor}
		$.ajax({
			url: '/getEstado',
			method: 'POST',
			contentType: "application/json",
			data: JSON.stringify({json}),
			success: function(result) {
				if (result==='4')
				{
					$( "#alert_estado" ).show("slow")
					
				}
				else
				{
					
					$( "#alert_estado" ).hide()
					
				}
			}
		});
	}
 }
 
 function getLinea() {
		$.ajax({
			url: '/getLinea',
			method: 'GET',
			contentType: "application/json",
			success: function(result) {
				$("#lineaActual").text(result);	
			}
		});
	
 }
 getLinea();
</script>